-- Create table and index
create table if not exists public.water_tests (
  id bigint generated by default as identity primary key,
  location text not null,
  latitude numeric(10, 6),
  longitude numeric(10, 6),
  ph numeric(5, 2) not null check (ph between 0 and 14),
  fluoride numeric(8, 3) not null check (fluoride >= 0),
  nitrates numeric(8, 2) not null check (nitrates >= 0),
  hardness numeric(8, 2) not null check (hardness >= 0),
  status text not null check (status in ('safe', 'caution', 'contaminated')),
  safety_score integer not null check (safety_score between 0 and 100),
  created_at timestamptz not null default now()
);

create index if not exists water_tests_created_at_idx on public.water_tests (created_at desc);

alter table public.water_tests enable row level security;

-- Safely recreate policies
drop policy if exists "Allow public inserts" on public.water_tests;
create policy "Allow public inserts" 
on public.water_tests 
for insert 
to anon 
with check (true);

drop policy if exists "Allow public read access" on public.water_tests;
create policy "Allow public read access" 
on public.water_tests 
for select 
to anon 
using (true);

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text unique,
  full_name text,
  age integer check (age is null or age between 13 and 120),
  mobile text,
  email text,
  avatar_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
drop policy if exists "Users can read own profile" on public.profiles;
create policy "Users can read own profile" on public.profiles for select to authenticated using (auth.uid() = id);
drop policy if exists "Users can create own profile" on public.profiles;
create policy "Users can create own profile" on public.profiles for insert to authenticated with check (auth.uid() = id);
drop policy if exists "Users can update own profile" on public.profiles;
create policy "Users can update own profile" on public.profiles for update to authenticated using (auth.uid() = id) with check (auth.uid() = id);

create table if not exists public.auth_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  event_type text not null check (event_type in ('signup', 'login', 'logout', 'otp_requested', 'otp_verified', 'oauth_login')),
  provider text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.auth_events enable row level security;
drop policy if exists "Users can create own auth events" on public.auth_events;
create policy "Users can create own auth events" on public.auth_events for insert to authenticated with check (auth.uid() = user_id);
drop policy if exists "Users can read own auth events" on public.auth_events;
create policy "Users can read own auth events" on public.auth_events for select to authenticated using (auth.uid() = user_id);

-- The service-role key bypasses RLS and is used only by server.cjs.
-- Add authenticated/public policies separately if the browser should query Supabase directly.