-- Create table and index
create table if not exists public.water_tests (
  id bigint generated by default as identity primary key,
  location text not null,
  latitude numeric(10, 6),
  longitude numeric(10, 6),
  ph numeric(5, 2) not null check (ph between 0 and 14),
  fluoride numeric(8, 3) not null check (fluoride >= 0),
  nitrates numeric(8, 2) not null check (nitrates >= 0),
  hardness numeric(8, 2) not null check (hardness >= 0),
  status text not null check (status in ('safe', 'caution', 'contaminated')),
  safety_score integer not null check (safety_score between 0 and 100),
  created_at timestamptz not null default now()
);

create index if not exists water_tests_created_at_idx on public.water_tests (created_at desc);

alter table public.water_tests enable row level security;

-- Safely recreate policies
drop policy if exists "Allow public inserts" on public.water_tests;
create policy "Allow public inserts" 
on public.water_tests 
for insert 
to anon 
with check (true);

drop policy if exists "Allow public read access" on public.water_tests;
create policy "Allow public read access" 
on public.water_tests 
for select 
to anon 
using (true);

-- The service-role key bypasses RLS and is used only by server.cjs.
-- Add authenticated/public policies separately if the browser should query Supabase directly.