import React, { Fragment, useEffect, useState } from 'react';
import { MapContainer, TileLayer, Circle, Polygon, Popup, Marker } from 'react-leaflet';
import L from 'leaflet';
import 'leaflet/dist/leaflet.css';
import { Layers, LocateFixed, Map as MapIcon } from 'lucide-react';
import { apiUrl } from '../api';

const colors = { safe: '#18b878', caution: '#f5b940', danger: '#f26d5b' };
const markerIcon = (status) => L.divIcon({ className: 'custom-marker', html: `<span style="background:${colors[status]}"></span>`, iconSize: [22, 22], iconAnchor: [11, 11] });

export default function BorewellMap({ locations }) {
  const [liveLocations, setLiveLocations] = useState([]); const [lastSynced, setLastSynced] = useState('Using community cache');
  const loadLiveTests = async () => { try { const response = await fetch(apiUrl('/api/tests')); if (!response.ok) throw new Error('API unavailable'); const records = await response.json(); setLiveLocations(records.map((record) => { const point = record.location || record; const normalizedStatus = String(record.status || 'safe').toLowerCase(); const status = normalizedStatus === 'contaminated' || normalizedStatus === 'warning' ? 'danger' : normalizedStatus === 'caution' ? 'caution' : 'safe'; return { id: `live-${record.id}`, name: typeof point === 'string' ? point : point.name || point.address || 'Community test point', type: 'Live test', lat: Number(point.lat ?? point.latitude), lng: Number(point.lng ?? point.longitude), score: record.safety_score ?? 0, status, tested: record.created_at, note: `F ${record.fluoride} mg/L · pH ${record.ph}` }; }).filter((record) => Number.isFinite(record.lat) && Number.isFinite(record.lng))); setLastSynced(`Live data · ${new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}`); } catch { setLastSynced('Using community cache'); } };
  useEffect(() => { loadLiveTests(); const refresh = () => loadLiveTests(); window.addEventListener('jalrakshak:test-created', refresh); const timer = window.setInterval(loadLiveTests, 30000); return () => { window.removeEventListener('jalrakshak:test-created', refresh); window.clearInterval(timer); }; }, []);
  const mergedLocations = [...locations, ...liveLocations.filter((live) => !locations.some((location) => location.id === live.id))];
  return <section className="panel map-panel"><div className="map-topline"><div><p className="eyebrow">Aquifer intelligence · {mergedLocations.length} live points</p><h2>North Bengaluru aquifer</h2></div><div className="map-actions"><button title="Refresh live tests" onClick={loadLiveTests}><LocateFixed size={16} /></button><button title="Map layers"><Layers size={16} /></button></div></div><div className="map-wrap"><MapContainer center={[13.021, 77.635]} zoom={14} scrollWheelZoom={true} zoomControl={false}>
    <TileLayer attribution='&copy; OpenStreetMap' url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png" />
    <Polygon positions={[[13.033, 77.625], [13.038, 77.648], [13.014, 77.655], [12.999, 77.641], [13.006, 77.621]]} pathOptions={{ color: '#f26d5b', fillColor: '#f26d5b', fillOpacity: 0.14, weight: 1.5, dashArray: '6 6' }} />
    {mergedLocations.map((location) => <Fragment key={location.id}><Circle center={[location.lat, location.lng]} radius={location.status === 'danger' ? 650 : 240} pathOptions={{ color: colors[location.status], fillColor: colors[location.status], fillOpacity: location.status === 'danger' ? 0.1 : 0.06, weight: 1 }} /><Marker position={[location.lat, location.lng]} icon={markerIcon(location.status)}><Popup><strong>{location.name}</strong><br /><span className={`popup-status ${location.status}`}>{location.status === 'danger' ? 'CONTAMINATED' : location.status.toUpperCase()}</span><br />Safety score: {location.score}/100<br /><small>{location.note}</small></Popup></Marker></Fragment>)}
  </MapContainer><div className="map-legend"><span><i className="dot safe" /> Safe</span><span><i className="dot caution" /> Caution</span><span><i className="dot danger" /> Contaminated plume</span></div><div className="plume-label"><span className="pulse-dot" /> Fluoride plume · expanding</div></div><div className="map-footer"><MapIcon size={15} /><span>Street-level monitoring</span><strong>{lastSynced}</strong></div></section>;
}
