import React, { Fragment, useEffect, useState } from 'react';
import { MapContainer, TileLayer, Circle, Polygon, Popup, Marker } from 'react-leaflet';
import L from 'leaflet';
import 'leaflet/dist/leaflet.css';
import { Layers, LocateFixed, Map as MapIcon } from 'lucide-react';
import { apiUrl } from '../api';

const colors = { safe: '#18b878', caution: '#f5b940', danger: '#f26d5b' };
const markerIcon = (status) => L.divIcon({ className: 'custom-marker', html: `<span style="background:${colors[status]}"></span>`, iconSize: [22, 22], iconAnchor: [11, 11] });
const mergeSameLocation = (records) => Object.values(records.reduce((groups, record) => { const key = `${record.lat.toFixed(4)}:${record.lng.toFixed(4)}`; const current = groups[key]; if (!current) return { ...groups, [key]: { ...record, logCount: 1 } }; const status = current.status === 'danger' || record.status === 'danger' ? 'danger' : current.status === 'caution' || record.status === 'caution' ? 'caution' : 'safe'; return { ...groups, [key]: { ...current, logCount: current.logCount + 1, status, score: Math.min(current.score, record.score), note: `Max readings · F ${Math.max(Number(current.fluoride) || 0, Number(record.fluoride) || 0)} mg/L · pH ${Math.max(Number(current.ph) || 0, Number(record.ph) || 0)}` } }; }, {}));

export default function BorewellMap({ locations }) {
  const [liveLocations, setLiveLocations] = useState([]); const [lastSynced, setLastSynced] = useState('Using community cache'); const [userLocation, setUserLocation] = useState(null); const [locationError, setLocationError] = useState('');
  const mapRef = React.useRef(null);
  const locateUser = () => { if (!navigator.geolocation) { setLocationError('Location is not available in this browser.'); return; } setLocationError('Finding your location...'); navigator.geolocation.getCurrentPosition(({ coords }) => { const point = { lat: coords.latitude, lng: coords.longitude, accuracy: coords.accuracy }; setUserLocation(point); setLocationError(''); mapRef.current?.flyTo([point.lat, point.lng], 15, { duration: 1.2 }); }, () => setLocationError('Allow location access to find yourself on the map.'), { enableHighAccuracy: true, timeout: 10000, maximumAge: 30000 }); };
  const loadLiveTests = async () => { try { const response = await fetch(apiUrl('/api/tests')); if (!response.ok) throw new Error('API unavailable'); const records = await response.json(); const mapped = records.map((record) => { const point = record.location || {}; const normalizedStatus = String(record.status || 'safe').toLowerCase(); const status = normalizedStatus === 'contaminated' || normalizedStatus === 'warning' ? 'danger' : normalizedStatus === 'caution' ? 'caution' : 'safe'; return { id: `live-${record.id}`, name: typeof point === 'string' ? point : point.name || point.address || 'Community test point', type: 'Live test', lat: Number((typeof point === 'object' ? point.lat ?? point.latitude : undefined) ?? record.latitude), lng: Number((typeof point === 'object' ? point.lng ?? point.longitude : undefined) ?? record.longitude), score: record.safety_score ?? 0, status, tested: record.created_at, fluoride: record.fluoride, ph: record.ph, note: `F ${record.fluoride} mg/L · pH ${record.ph}` }; }).filter((record) => Number.isFinite(record.lat) && Number.isFinite(record.lng)); setLiveLocations(mergeSameLocation(mapped)); setLastSynced(`Live data · ${new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}`); } catch { setLastSynced('Using community cache'); } };
  useEffect(() => { loadLiveTests(); const refresh = (event) => { const point = event.detail; if (point && Number.isFinite(Number(point.latitude)) && Number.isFinite(Number(point.longitude))) { const contaminated = Number(point.fluoride) > 1.5 || Number(point.ph) < 6.5 || Number(point.ph) > 8.5; const pointStatus = contaminated ? 'danger' : Number(point.nitrates) > 45 || Number(point.hardness) > 600 ? 'caution' : 'safe'; setLiveLocations((current) => mergeSameLocation([{ id: `local-${Date.now()}`, name: point.location || 'Current photo location', type: 'Live test', lat: Number(point.latitude), lng: Number(point.longitude), score: point.score ?? 0, status: pointStatus, tested: new Date().toISOString(), fluoride: point.fluoride, ph: point.ph, note: `F ${point.fluoride} mg/L · pH ${point.ph}` }, ...current])); } window.setTimeout(loadLiveTests, 1000); }; window.addEventListener('jalrakshak:test-created', refresh); const timer = window.setInterval(loadLiveTests, 30000); return () => { window.removeEventListener('jalrakshak:test-created', refresh); window.clearInterval(timer); }; }, []);
  const mergedLocations = [...locations, ...liveLocations.filter((live) => !locations.some((location) => location.id === live.id))];
  useEffect(() => { const points = mergedLocations.filter((location) => Number.isFinite(location.lat) && Number.isFinite(location.lng)); if (!mapRef.current || !points.length) return; mapRef.current.fitBounds(L.latLngBounds(points.map((point) => [point.lat, point.lng])), { padding: [24, 24], maxZoom: 14 }); }, [liveLocations, locations]);
  return <section className="panel map-panel"><div className="map-topline"><div><p className="eyebrow">India community network · {mergedLocations.length} live points</p><h2>Water intelligence across India</h2></div><div className="map-actions"><button title="Find my live location" onClick={locateUser}><LocateFixed size={16} /></button><button title="Refresh live tests" onClick={loadLiveTests}><Layers size={16} /></button></div></div><div className="map-wrap"><MapContainer ref={mapRef} center={[22.5, 79]} zoom={5} scrollWheelZoom={true} zoomControl={false}>
    <TileLayer attribution='&copy; OpenStreetMap' url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png" />
    <Polygon positions={[[13.033, 77.625], [13.038, 77.648], [13.014, 77.655], [12.999, 77.641], [13.006, 77.621]]} pathOptions={{ color: '#f26d5b', fillColor: '#f26d5b', fillOpacity: 0.14, weight: 1.5, dashArray: '6 6' }} />
    {mergedLocations.map((location) => <Fragment key={location.id}><Circle center={[location.lat, location.lng]} radius={location.status === 'danger' ? 650 : 240} pathOptions={{ color: colors[location.status], fillColor: colors[location.status], fillOpacity: location.status === 'danger' ? 0.1 : 0.06, weight: 1 }} /><Marker position={[location.lat, location.lng]} icon={markerIcon(location.status)}><Popup><strong>{location.name}</strong><br /><span className={`popup-status ${location.status}`}>{location.status === 'danger' ? 'CONTAMINATED' : location.status.toUpperCase()}</span><br />{location.logCount || 1} log(s) at this location<br />Safety score: {location.score}/100<br /><small>{location.note}</small></Popup></Marker></Fragment>)}{userLocation && <><Circle center={[userLocation.lat, userLocation.lng]} radius={userLocation.accuracy} pathOptions={{ color: '#268cff', fillColor: '#268cff', fillOpacity: 0.12, weight: 1 }} /><Marker position={[userLocation.lat, userLocation.lng]} icon={L.divIcon({ className: 'user-location-marker', html: '<span></span>', iconSize: [24, 24], iconAnchor: [12, 12] })}><Popup><strong>Your live location</strong><br /><small>Accuracy: approximately {Math.round(userLocation.accuracy)} m</small></Popup></Marker></>}
  </MapContainer><div className="map-legend"><span><i className="dot safe" /> Safe</span><span><i className="dot caution" /> Caution</span><span><i className="dot danger" /> Contaminated plume</span><span><i className="dot user-dot" /> You</span></div><div className="plume-label"><span className="pulse-dot" /> Fluoride plume · expanding</div></div>{locationError && <p className="location-status map-location-status">{locationError}</p>}<div className="map-footer"><MapIcon size={15} /><span>Street-level monitoring</span><strong>{lastSynced}</strong></div></section>;
}
