import React, { useEffect, useRef, useState } from 'react';
import { Camera, Check, FlipHorizontal2, ScanLine, ShieldAlert } from 'lucide-react';
import { apiUrl } from '../api';

const metrics = [
  { key: 'fluoride', label: 'Fluoride', unit: 'mg/L', limit: 1.5, reference: [[238, 225, 102, 0], [218, 164, 74, 0.8], [185, 88, 71, 1.8], [117, 55, 74, 3]] },
  { key: 'ph', label: 'pH', unit: 'scale', limit: 8.5, reference: [[235, 157, 183, 5.5], [218, 104, 146, 6.5], [128, 180, 160, 7.4], [69, 125, 181, 8.5], [61, 77, 143, 9.5]] },
  { key: 'nitrates', label: 'Nitrates', unit: 'mg/L', limit: 45, reference: [[232, 224, 166, 0], [218, 191, 100, 25], [214, 131, 74, 45], [178, 72, 65, 80]] },
  { key: 'hardness', label: 'Hardness', unit: 'mg/L', limit: 600, reference: [[173, 215, 180, 100], [112, 190, 174, 300], [62, 136, 160, 600], [50, 87, 125, 1000]] },
];

export function parseStripColor(red, green, blue) {
  let ph = 7;
  if (red > 200 && green < 100) ph = 9;
  else if (red > 180 && green > 180) ph = 6.5;
  return { ph, fluoride: Number((red / 100).toFixed(1)), nitrates: Math.round(green * 0.4), hardness: Math.round(blue * 4) };
}

export default function Scanner({ onScan }) {
  const videoRef = useRef(null); const canvasRef = useRef(null); const streamRef = useRef(null);
  const [active, setActive] = useState(false); const [captured, setCaptured] = useState(false); const [error, setError] = useState(''); const [facingMode, setFacingMode] = useState('environment');
  const [values, setValues] = useState({ fluoride: '', ph: '', nitrates: '', hardness: '' });

  useEffect(() => () => streamRef.current?.getTracks().forEach((track) => track.stop()), []);
  const startCamera = async (mode = facingMode) => { try { streamRef.current?.getTracks().forEach((track) => track.stop()); const stream = await navigator.mediaDevices?.getUserMedia({ video: { facingMode: { ideal: mode }, width: { ideal: 1280 } } }); if (!stream) throw new Error('Camera API unavailable'); streamRef.current = stream; if (videoRef.current) videoRef.current.srcObject = stream; setActive(true); setError(''); } catch { setError('Camera unavailable. Use the demo scan to continue.'); } };
  const averageRgb = (context, x, y, width, height) => { const pixels = context.getImageData(x, y, width, height).data; const rgb = [0, 0, 0]; let count = 0; for (let index = 0; index < pixels.length; index += 4) { rgb[0] += pixels[index]; rgb[1] += pixels[index + 1]; rgb[2] += pixels[index + 2]; count += 1; } return rgb.map((channel) => Math.round(channel / count)); };
  const nearestValue = (rgb, reference) => reference.reduce((best, point) => { const distance = Math.hypot(rgb[0] - point[0], rgb[1] - point[1], rgb[2] - point[2]); return distance < best.distance ? { distance, value: point[3] } : best; }, { distance: Infinity, value: reference[0][3] }).value;
  const calculateScore = (nextValues) => Math.max(0, 100 - (Number(nextValues.fluoride) > 1.5 ? 45 : 0) - (Number(nextValues.ph) < 6.5 || Number(nextValues.ph) > 8.5 ? 25 : 0) - (Number(nextValues.nitrates) > 45 ? 15 : 0) - (Number(nextValues.hardness) > 600 ? 10 : 0));
  const saveScan = (result) => navigator.geolocation?.getCurrentPosition(async ({ coords }) => { try { await fetch(apiUrl('/api/tests'), { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ location: `Browser scan point (${coords.latitude.toFixed(5)}, ${coords.longitude.toFixed(5)})`, ...result, status: Number(result.fluoride) > 1.5 || Number(result.ph) < 6.5 || Number(result.ph) > 8.5 ? 'contaminated' : 'safe' }) }); } catch { /* The local result remains available when the API is offline. */ } });
  const capture = () => { const video = videoRef.current; const canvas = canvasRef.current; if (!video || !canvas || !video.videoWidth) return; canvas.width = video.videoWidth; canvas.height = video.videoHeight; const context = canvas.getContext('2d', { willReadFrequently: true }); context.drawImage(video, 0, 0, canvas.width, canvas.height); const centerPixel = context.getImageData(Math.floor(canvas.width / 2), Math.floor(canvas.height / 2), 1, 1).data; const centerEstimate = parseStripColor(centerPixel[0], centerPixel[1], centerPixel[2]); const samples = metrics.map((metric, index) => { const x = Math.round(canvas.width * (0.22 + index * 0.19)); const y = Math.round(canvas.height * 0.45); return [metric, averageRgb(context, Math.max(0, x - 10), Math.max(0, y - 10), 20, 20)]; }); const nextValues = Object.fromEntries(samples.map(([metric, rgb]) => [metric.key, nearestValue(rgb, metric.reference)])); const result = { ...nextValues, score: calculateScore(nextValues), centerRgb: { red: centerPixel[0], green: centerPixel[1], blue: centerPixel[2] }, centerEstimate }; setValues(nextValues); setCaptured(true); onScan(result); saveScan(result); window.dispatchEvent(new CustomEvent('jalrakshak:test-created', { detail: result })); };
  const switchCamera = () => { const nextMode = facingMode === 'environment' ? 'user' : 'environment'; setFacingMode(nextMode); if (active) startCamera(nextMode); };
  const updateValue = (key, value) => { const nextValues = { ...values, [key]: value }; setValues(nextValues); if (Object.values(nextValues).every((current) => current !== '')) onScan({ ...nextValues, score: calculateScore(nextValues) }); };
  return <section className="panel scanner-panel"><div className="section-heading"><div><p className="eyebrow">Browser vision · RGB strip parse</p><h2>Scan a water strip</h2></div><span className="scan-status"><span /> {captured ? 'Parsed' : 'Ready'}</span></div><div className="camera-stage">{active && <video ref={videoRef} autoPlay muted playsInline />}{!active && <div className="camera-placeholder"><Camera size={28} /><strong>Align your strip in the frame</strong><span>Use a standard 5-parameter test strip</span></div>}<div className="scan-frame"><span /><span /><span /><span /><div className="scan-line" /></div><div className="camera-hud"><span><ScanLine size={14} /> RGB sampling zone</span><span>1.2 ×</span></div></div><canvas ref={canvasRef} className="scan-canvas" /><div className="scanner-controls"><button className="round-control" title="Switch camera" onClick={switchCamera}><FlipHorizontal2 size={17} /></button><button className="capture-button" onClick={active ? capture : startCamera}><span>{captured ? <Check size={21} /> : <Camera size={21} />}</span>{captured ? 'Scan again' : active ? 'Capture frame' : 'Open camera'}</button><span className="secure-note"><ShieldAlert size={14} /> On-device</span></div>{error && <p className="camera-error">{error} <button onClick={() => { const demo = { fluoride: 1.8, ph: 7.4, nitrates: 29, hardness: 340 }; setValues(demo); setCaptured(true); onScan({ ...demo, score: 54 }); }}>Use demo scan</button></p>}<div className="metric-grid">{metrics.map((metric) => <label className="metric" key={metric.key}><span>{metric.label}</span><input className="metric-input" type="number" step="any" value={values[metric.key]} onChange={(event) => updateValue(metric.key, event.target.value)} placeholder="--" aria-label={metric.label} /><small>{metric.unit}</small></label>)}</div></section>;
}
