import React, { useState } from 'react';
import { Bell, ChevronDown, Droplets, Menu, Moon, Plus, Radio, ShieldCheck, Sun, UserRound } from 'lucide-react';
import BorewellMap from './components/BorewellMap';
import HealthAlerts from './components/HealthAlerts';
import ImpactStats from './components/ImpactStats';
import Scanner from './components/Scanner';
import TankerRegistry from './components/TankerRegistry';
import { borewells, defaultScan, tankers } from './data';

export default function App() {
  const [dark, setDark] = useState(false); const [scan, setScan] = useState(defaultScan); const [menuOpen, setMenuOpen] = useState(false);
  return <div className={dark ? 'app dark' : 'app'}><header className="topbar"><a className="brand" href="#top"><span className="brand-mark"><Droplets size={19} /></span><span>Jal<span>Rakshak</span></span></a><nav><a className="active" href="#overview">Overview</a><a href="#map">Live map</a><a href="#scan">Scan strip</a><a href="#registry">Registry</a></nav><div className="top-actions"><button className="icon-button" title="Toggle theme" onClick={() => setDark(!dark)}>{dark ? <Sun size={17} /> : <Moon size={17} />}</button><button className="icon-button notification" title="Notifications"><Bell size={17} /><i /></button><div className="profile"><span>AK</span><strong>Ananya K.</strong><ChevronDown size={14} /></div><button className="menu-button" onClick={() => setMenuOpen(!menuOpen)}><Menu size={19} /></button></div></header>{menuOpen && <div className="mobile-nav"><a href="#overview">Overview</a><a href="#map">Live map</a><a href="#scan">Scan strip</a><a href="#registry">Registry</a></div>}<main id="top"><section className="hero" id="overview"><div><div className="live-label"><Radio size={14} /> Community network live <span>·</span> North Bengaluru</div><h1>Know your water.<br /><em>Protect your neighbourhood.</em></h1><p className="hero-copy">JalRakshak turns everyday water tests into a shared early-warning network for families, farms, and the aquifer below.</p><div className="hero-actions"><button className="primary-button" onClick={() => document.getElementById('scan').scrollIntoView({ behavior: 'smooth' })}><Plus size={17} /> Log a new test</button><span className="sync-note"><ShieldCheck size={16} /> 96% data verified</span></div></div><div className="hero-score"><div className="score-ring"><strong>78</strong><span>network<br />health</span></div><div><span>Last 24 hours</span><strong className="score-up">↑ 6.2%</strong></div></div></section><ImpactStats /><div className="section-grid" id="map"><BorewellMap locations={borewells} /><div className="side-column"><HealthAlerts scan={scan} /><div className="coverage panel"><div><p className="eyebrow">Neighbourhood pulse</p><h2>Coverage this week</h2></div><div className="coverage-number"><strong>82%</strong><span>of mapped homes</span></div><div className="progress"><span /></div><p className="muted-copy">24 new tests logged across 6 streets. Keep the network growing.</p></div></div></div><div className="lower-grid" id="scan"><Scanner onScan={setScan} /><TankerRegistry tankers={tankers} /></div></main><footer><span>JalRakshak <b>·</b> Community water intelligence</span><span>Data is crowdsourced and should be confirmed by a certified lab.</span><span className="footer-links">Privacy · Guidelines</span></footer></div>;
}
